from app.models.user import User
from app.models.student import Student
from app.models.lecturer import Lecturer
from app.models.course import Course
from app.models.class_section import ClassSection
from app.models.enrollment import Enrollment
from app.models.schedule import Schedule
from app.models.attendance_session import AttendanceSession
from app.models.attendance_record import AttendanceRecord