"""create attendance system tables

Revision ID: 847814d488bb
Revises: 
Create Date: 2026-09-10 10:43:10.813007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847814d488bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('courseID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courseCode', sa.String(length=20), nullable=False),
    sa.Column('courseName', sa.String(length=150), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('courseID'),
    sa.UniqueConstraint('courseCode')
    )
    op.create_table('users',
    sa.Column('userID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('lecturers',
    sa.Column('lecturerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('lecturerCode', sa.String(length=20), nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('lecturerID'),
    sa.UniqueConstraint('lecturerCode'),
    sa.UniqueConstraint('userID')
    )
    op.create_table('students',
    sa.Column('studentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('studentCode', sa.String(length=20), nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['users.userID'], ),
    sa.PrimaryKeyConstraint('studentID'),
    sa.UniqueConstraint('studentCode'),
    sa.UniqueConstraint('userID')
    )
    op.create_table('class_sections',
    sa.Column('classID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('courseID', sa.Integer(), nullable=False),
    sa.Column('lecturerID', sa.Integer(), nullable=False),
    sa.Column('classCode', sa.String(length=30), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('academicYear', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['courseID'], ['courses.courseID'], ),
    sa.ForeignKeyConstraint(['lecturerID'], ['lecturers.lecturerID'], ),
    sa.PrimaryKeyConstraint('classID'),
    sa.UniqueConstraint('classCode')
    )
    op.create_table('attendance_sessions',
    sa.Column('sessionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classID', sa.Integer(), nullable=False),
    sa.Column('sessionDate', sa.Date(), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=False),
    sa.Column('endTime', sa.Time(), nullable=False),
    sa.Column('attendanceMethod', sa.String(length=20), nullable=False),
    sa.Column('attendancePasswordHash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['classID'], ['class_sections.classID'], ),
    sa.PrimaryKeyConstraint('sessionID')
    )
    op.create_table('enrollments',
    sa.Column('enrollmentID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('classID', sa.Integer(), nullable=False),
    sa.Column('enrollmentDate', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['classID'], ['class_sections.classID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('enrollmentID')
    )
    op.create_table('schedules',
    sa.Column('scheduleID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classID', sa.Integer(), nullable=False),
    sa.Column('dayOfWeek', sa.String(length=20), nullable=False),
    sa.Column('startTime', sa.Time(), nullable=False),
    sa.Column('endTime', sa.Time(), nullable=False),
    sa.Column('room', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['classID'], ['class_sections.classID'], ),
    sa.PrimaryKeyConstraint('scheduleID')
    )
    op.create_table('attendance_records',
    sa.Column('attendanceID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sessionID', sa.Integer(), nullable=False),
    sa.Column('studentID', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checkInTime', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sessionID'], ['attendance_sessions.sessionID'], ),
    sa.ForeignKeyConstraint(['studentID'], ['students.studentID'], ),
    sa.PrimaryKeyConstraint('attendanceID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_records')
    op.drop_table('schedules')
    op.drop_table('enrollments')
    op.drop_table('attendance_sessions')
    op.drop_table('class_sections')
    op.drop_table('students')
    op.drop_table('lecturers')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
